### ISSUE TITLE
installation is not successful due to bug in setup file.

### ISSUE THREAD

**Issue by sabiharustam** [hernanchavezthielemann/GRO2LAM#18]
**Describe the bug**
in the setup file : 
1. line 18: print function missing parenthesis. 
2. line 45: print 'Checking installation files for {}'.format(__version__) . Gives syntax error, still, cause of missing parenthesis.
3. There are lots of print commands that are missing the parenthesis.
4. After I manually added parenthesis to all the print commands, there was another error message. Please see screenshots.

**To Reproduce**
1. Go to 'README.md' on the main page.
2. In step by step installation information.
3. Scroll down to '~$ python setup'
4. execution of the command gives you the error listed above.

**Expected behavior**
Be able to run the setup file without error.

**Screenshots**
After manually adding the parenthesis to print function. Rerunning the setup gives me this error message.
![image](https://user-images.githubusercontent.com/41701306/56925927-5d4c8000-6a85-11e9-95ab-ac7eab68167e.png)

**Desktop (please complete the following information):**
 - UW Hyak supercomputer. Linux64 system.
- Python 3.6

**Additional context**

>> Try to isolate the issue ;)

**Comment by hernanchavezthielemann** [comment]
Hi Sabiha,

Thank you for this nice bug report!

Everything is ultra clear:
 - GRO2LAM was started when python 2 used to come as default.
 - GRO2LAM is a Python 2.7 code.
 - Python 3.x is your default python.

Solution:
 - I already change the auto installer to run it explicitly with python 2, so now should work.
 - Your computer probably has a version of Python 2.7, if not you have to install one.

Best regards,
Hernan
