### ISSUE TITLE
Atoms, Bonds, etc missing in the generated data file

### ISSUE THREAD

**Issue by l454025801** [hernanchavezthielemann/GRO2LAM#26]
**Describe the bug**
Information about Atoms, Bonds, Angels, etc. is missing in the generated data.gro2lam file.

**To Reproduce**
1. Select gro, top, forcefield, bonded, nonbonded files
2. Choose Atom type 'full'
3. Click 'Convert'

**Expected behavior**
A data file containing all info should be generated.

**Screenshots**

![Screenshot from 2020-02-17 10-35-08](https://user-images.githubusercontent.com/60527575/74671723-6c660100-5171-11ea-8023-a390088d0427.png)

**Desktop (please complete the following information):**
Python 3

>> Try to isolate the issue ;)

**Comment by hernanchavezthielemann** [comment]
Hi Yang,

Thanks for your feedback.
Would be great to have more info about your data files, like bond- angle- kind.

However, I have to point that GRO2LAM is a python **2.7** program.

Nevertheless, if it is running and generating some output, I would say that you have to use the "autoload" function, because, with the current input something is missing.

Best regards,
Hernan

**Comment by l454025801** [comment]
Hello!

I have tried as you suggested but problems still occurs.
1. I ran GRO2LAM in python2.7 environment but the same error occurred (info about atom, bond, etc,. missing).

2. I tried the autoload function but it gave me errors. Screenshot are attached. I have checked topology file, the sequence is consistent with .gro file. According to the error info, it seems something wrong with the water topology, but I cannot figure it out.

3. For the input files, the types are:
   bond           -- func 1
   constraint   -- func 2
   angel          -- func 5 (Urey-Bradley)
   dihedral      -- func 9 (proper dihedral (multiple)) & func 2 (improper dihedral)
   

  #Error info
![Screenshot from 2020-02-18 09-33-20](https://user-images.githubusercontent.com/60527575/74753706-232bb500-5236-11ea-8b6c-579308e3e93f.png)
 #Top file
![Screenshot from 2020-02-18 09-32-50](https://user-images.githubusercontent.com/60527575/74753708-23c44b80-5236-11ea-96f2-1eeeb04584f7.png)
![Screenshot from 2020-02-18 09-33-09](https://user-images.githubusercontent.com/60527575/74753709-23c44b80-5236-11ea-9b3f-5e45081d0cba.png)

**Comment by hernanchavezthielemann** [comment]
Hi Yang,

Considering the screenshots, I would say that the problem comes from your "**gro**" file. Because in your "**top**" you have a molecule named SOL, with a residue called SOL, which is the default for water. However, in your "**gro**" you name that water residue as HOH.

So changing HOH tag in your "**gro**" by SOL should make it.

Best,
Hernan

**Comment by l454025801** [comment]
Hi!

Sorry to trouble again.
The warning says missing coefficients about HC. Since it did not mention any other atom, I am assuming there are something missing about HC in atom definition. I checked the [atomtypes] in the nonbonded.itp. Everything seems right.

![Screenshot from 2020-02-13 14-56-46](https://user-images.githubusercontent.com/60527575/74783464-5fc5d380-526b-11ea-9fd2-bc90d99f86c9.png)
![Screenshot from 2020-02-18 16-21-35](https://user-images.githubusercontent.com/60527575/74783465-5fc5d380-526b-11ea-8793-74a9f1bf4180.png)
![Screenshot from 2020-02-18 16-22-25](https://user-images.githubusercontent.com/60527575/74783466-605e6a00-526b-11ea-8cf8-c00274b8cb93.png)

Thank you !!

**Comment by hernanchavezthielemann** [comment]
I think that is better if you upload a test case of your files here. Then I can check.

**Comment by hernanchavezthielemann** [comment]
Yang? @l454025801

**Comment by l454025801** [comment]
Hi Hernan,

Sorry that I haven been busy and didn't check replies for a while.
Attached is the files.
Appreciate for your patience and help!

Thank you
[T298.zip](https://github.com/hernanchavezthielemann/GRO2LAM/files/4233116/T298.zip)

**Comment by hernanchavezthielemann** [comment]
Hi Yang,

I have checked your files, and what comes out is that there are some dihedrals and impropers missing in your bonded coefficients.
Now, I have added extra verbose in that error, so you can check with the new version of GRO2LAM which parameters are missing in your input data.

Best, 
Hernan

**Comment by hernanchavezthielemann** [comment]
Hi @l454025801 

Please let me know if you solve the problem.

Best,
Hernan

**Comment by l454025801** [comment]
Hi Hernan,

Sorry that I have decided to use other software instead of lammps since I am doing all atom simulation.

Thanks
Yang
