### ISSUE TITLE
Compatibility with Python3? 

### ISSUE THREAD

**Issue by KevinKongWisc** [hernanchavezthielemann/GRO2LAM#48]
Hi, is there any possibility that a python3 version will be released? Thank you!

**Comment by hernanchavezthielemann** [comment]
Hi @KevinKongWisc,

Thanks for your question.
Indeed the released beta-beta version works just fine in python3.
I just have to do some formality checks and change a little the setup to ask for tkinter package in python3, but I think that package comes by default now, so GRO2LAM should work if you have a healthy installation of python3.
You can install the beta-beta with the following command line in Linux:

`wget https://raw.githubusercontent.com/hernanchavezthielemann/utils/master/grotolam/G2L_iBeta && bash G2L_iBeta`

Best regards,
Hernan
