### ISSUE TITLE
Question: receiving error in lammps.py: atoms order mismatch between residue definition and gro file 

### ISSUE THREAD

**Issue by Bellsthescientist** [hernanchavezthielemann/GRO2LAM#62]
Hi, 

I've been struggling with this for a while and I don't know what the issue is. My first atom in gro file is TiA and my residue definition in [atoms] is also TiA. Where am I going wrong? I will attach all relevant files below. I cannot seem to complete the conversion. 
[dotgrofile.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567863/dotgrofile.txt)
[residue.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567839/residue.txt)

OTHER: 
[BonesFFitp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567841/BonesFFitp.txt)
[topfile.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567842/topfile.txt)
[defaultsitpfile.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567843/defaultsitpfile.txt)
[nonbondeditp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567849/nonbondeditp.txt)
[bondeditp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567850/bondeditp.txt)
[originalpdb.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567851/originalpdb.txt)

**Comment by Bellsthescientist** [comment]
[dotgrofile.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/11567861/dotgrofile.txt)

**Comment by hernanchavezthielemann** [comment]
Hi Bell
sorry... since you did not tag me in the conversation, I did not receive any notification, thus I didn't notice this question until now.
Please let me know if you are still looking at this.
Best,
Hernan.

**Comment by meghaparashar2** [comment]
Dear @hernanchavezthielemann 
I also am struggling with the same issue and not able to complete the conversion.

Here are the files
[bonitp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12713038/bonitp.txt)
[forcefielditp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12713039/forcefielditp.txt)
[mchitp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12713040/mchitp.txt)
[nbitp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12713041/nbitp.txt)
[topology.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12713042/topology.txt)

Can you please help with this?

Thanks,
Megha
