### ISSUE TITLE
Can't generate Atoms #atomic in data output file for lammps

### ISSUE THREAD

**Issue by lje1234** [hernanchavezthielemann/GRO2LAM#63]
Hello,

I have compiled GRO2LAM onto my computer and am able to ./run to use the GUI. At the "Data File Creation" step, I upload my .gro, .top, and my 3 forcefield files. However, when the GUI processes these files, the data output file reports 0 atoms and does not list any of my atoms from my .gro file. 

This system is an ionic liquid with two different molecules. It should report 48096 atoms. The cation EMI should have 2004 mols and similarly, the anion should have 2004 mols. 

To reproduce the error, I have attached my 5 files (forcefield.itp, ffbonded.itp, ffnonbonded.itp, EMIM_BF4.gro and EMIM_BF4.top) [all converted into .txt files to be able to upload] and a 6th file that is called BF4_bonded_scale0.8.itp to include the BF4 topology file. I have tried to make this as analogous to the CNT example where my BF4_bonded_scale0.8.itp is the spce.itp file. I ran these 5 files (and not sure if the #include is reading the 6th BF4 topology file due to conflicting evidence) in the gro2lam GUI. I am pretty sure this is an issue with the EMIM_BF4.top and file with the #include, but I do not know how to fix this.  Any help is appreciated! 

[EMIM_BF4_top.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12564205/EMIM_BF4_top.txt)
[EMIM_BF4_gro.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12564208/EMIM_BF4_gro.txt)
[BF4_bonded_scale0.8_itp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12564210/BF4_bonded_scale0.8_itp.txt)
[forcefield_itp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12564217/forcefield_itp.txt)
[ffbonded_itp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12564214/ffbonded_itp.txt)
[ffnonbonded_itp.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12564216/ffnonbonded_itp.txt)

output:
[data.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12564219/data.txt)

**Comment by hernanchavezthielemann** [comment]
Hi Lj,
I will try to look at it at some near point in time,
Did it produce any kind of error or warning in the terminal?
best,
Hernan.

**Comment by lje1234** [comment]
Hi Hernan,

Thank you for your reply. Yes, there were a couple of warnings. On the GUI, it warns me about proceeding without autoload. In the terminal, I have 5 warnings:

Warning!! -- Proceeding without autoload.
This means that any internal address to files that are not specified as GUI input are going to be ignored.
Warning!! -- Using pure side molecule scheme
Warning!! -- ['#ifdef', 'HEAVY_H']  ??
Warning!! -- ['#else']  ??
Warning!! -- ['#endif']  ??

Terminal is also in the screenshot in the images below.
![image](https://github.com/hernanchavezthielemann/GRO2LAM/assets/144499310/e012c2ee-4de5-4769-b4ed-b99ad20f986d)
![image](https://github.com/hernanchavezthielemann/GRO2LAM/assets/144499310/dfe443d2-5d83-498c-8738-bb7d24245a8c)

Thank you!

-Lisa

**Comment by hernanchavezthielemann** [comment]
Hi Lisa,
I have just checked the files, but it seems to me that the TOP is indeed the GRO... but the GRO is the GRO :).
maybe this is just a mistake while uploading? could you please check that?
Best,
Hernan.

**Comment by lje1234** [comment]
Hi Hernan,

Hi Hernan,

Yes sorry, that was a mistake (they are both named EMIM_BF4). I apologize and have correctly uploaded the EMIM_BF4.gro and EMIM_BF4.top below. 
[EMIM_BF4_top.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12566649/EMIM_BF4_top.txt)
[EMIM_BF4_gro.txt](https://github.com/hernanchavezthielemann/GRO2LAM/files/12566650/EMIM_BF4_gro.txt)


Best,
Lisa

**Comment by hernanchavezthielemann** [comment]
Hi Lisa,

I just checked it, and found some format problems, and missing potentials.
In general the directive definitions should be between square brackets, like "[ directive ]", with just one space between bracket and the directive keyword.
Then the residue BF4 was called just BF in the residue atom definition.
and then GRO2LAM finds that there are some missing potentials, thus you have to check that.
I have attached a working version, that might lead you to find the missing potentials.
by the way, since you have the extra molecule, you have to proceed with the autoload button.

Best,
Hernan.

[Lisa.zip](https://github.com/hernanchavezthielemann/GRO2LAM/files/12568426/Lisa.zip)

**Comment by lje1234** [comment]
Hi Hernan,

Thank you. I've just tried the zip file and it was able to convert the atoms correctly. I will make sure to put the directives in with just one space between the brackets. 

I will work on the missing potentials now but this problem has been resolved. Thank you very much again.

Best,
Lisa

**Comment by hernanchavezthielemann** [comment]
Hi Lisa,
You are welcome, have nice simulations!
best,
Hernan
